### PR TITLE
Use conda environments for R scripts

### LINKED ISSUE #24: Support dependency versioning for R
Dependency management should be officially supported by the pipeline engine, and properly documented.

### PR DESCRIPTION
**Pull request by jmlord**
This uses a global conda environment, and supports specific conda environment for scripts.

See updated doc for details.

Linked to https://github.com/GEO-BON/bon-in-a-box-pipelines/pull/152
closes #24

### CODE REVIEW

**Review by glaroc — APPROVED** [review]

**Comment by jmlord** [comment]
@JoryGriffith to test this:
checkout branch conda2, then start the server with the following command:
`./server-up.sh conda`
You can check the diff of the readme to ge the new instructions and check if they are complete enough, or if anything else needs to be modified.

**Comment by jmlord** [comment]
closes #113

**Comment by jmlord** [comment]
Need to add message if pipeline repo doesn't have the conda stuff.

**Comment by glaroc** [comment]
I did a clean clone of pipeline-repo, launched it from the main branch with server-up.sh, closed it, switched to the conda2 branch, did a `./server-up.sh staging` and when I run the Maxent pipeline, I get

```
bash: line 26: /conda-env-yml/data__loadFromStac.yml: Permission denied
Creating new conda environment data__loadFromStac
FAILED
```

**Comment by jmlord** [comment]
> I did a clean clone of pipeline-repo, launched it from the main branch with server-up.sh, closed it, switched to the conda2 branch, did a `./server-up.sh staging` and when I run the Maxent pipeline, I get
> 
> ```
> bash: line 26: /conda-env-yml/data__loadFromStac.yml: Permission denied
> Creating new conda environment data__loadFromStac
> FAILED
> ```

For the records: the above was due to a conda runner out of sync with the server. The conda runner is not yet built automatically since it's not on the main branch.

**Pull request merged**
