### PR TITLE
Add load R input and output functions

### LINKED ISSUE #83: Load inputs automatically from json in R and save outputs through function
Instead of each script implementing code to load inputs and save outputs, add the following line in R before running any R script: 

````
biab_inputs <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file
````

We could also write and load a function that saves the output

````
biab_save_outputs <- function(outputs_list){
      setwd(outputFolder)
      write(rjson::toJSON(outputs_list), 'output.json')
}
````
The documentation would have to be adapted accordingly.

### PR DESCRIPTION
**Pull request by glaroc**
closes #83

### CODE REVIEW

**Comment by jmlord** [comment]
We'd need to add documentation to the qmds about it and change a few scripts to use it.

**Comment by glaroc** [comment]
We can't change a few scripts to use it until this is merged. I changed the documentation for R to use these functions.

**Comment by jmlord** [comment]
Comment from @JoryGriffith : good time to add an error function as well.

**Comment by jmlord** [comment]
> Did we want this merged before COP ?

Right after COP I think, then we can go over all the merged pipelines.

**Comment by JoryGriffith** [comment]
Looks good

**Review by JoryGriffith — APPROVED** [review]

**Pull request merged**
