### PR TITLE
jpeg vs jpg

### PR DESCRIPTION
**Pull request by glaroc**

### CODE REVIEW

**Comment by jmlord** [comment]
This will not work for all image types. 
See https://github.com/GEO-BON/bon-in-a-box-pipeline-engine/blob/0b2aee9b58b9b70494996a675bd4602d67b2411f/ui/src/components/StepResult.jsx#L118

The two viewers is a bit problematic: one fully recursive the other not, one displays multiband tiffs the other not, image types supported are not all the same, etc.

**Review by jmlord — APPROVED** [review]

**Comment by glaroc** [comment]
Browsers don't support all image mime-types. I don't think it's a good idea to blankly assume we can support them all.

**Comment by jmlord** [comment]
There is a table but it doesn't look up to date: https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support
(the same will happen to our code :P )

Worst case it appears as a broken image. But probabilities are that files generated by our scripts will fall in the common formats.
At least svg, bmp and gif would be nice to support too.

**Comment by glaroc** [comment]
There are a number of geospatial formats that have image/ as well, and we simply don't want to display them in the browser. I would prefer if we just listed the file types one by one. I can add svg and gif.

**Pull request merged**
